/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package package

import (
	"context"

	"github.com/pkg/errors"
	"github.com/google/go-cmp/cmp"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
	svcsdkapi "github.com/aws/aws-sdk-go/service/elasticsearchservice/elasticsearchserviceiface"
	svcapi "github.com/aws/aws-sdk-go/service/elasticsearchservice"
	svcsdk "github.com/aws/aws-sdk-go/service/elasticsearchservice"

	"github.com/crossplane/crossplane-runtime/pkg/meta"
	"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed"
	cpresource "github.com/crossplane/crossplane-runtime/pkg/resource"
	xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"

	svcapitypes "github.com/crossplane/provider-aws/apis/elasticsearchservice/v1alpha1"
	awsclient "github.com/crossplane/provider-aws/pkg/clients"
)

const (
	errUnexpectedObject = "managed resource is not an Package resource"

	errCreateSession = "cannot create a new session"
	errCreate = "cannot create Package in AWS"
	errUpdate = "cannot update Package in AWS"
	errDescribe = "failed to describe Package"
	errDelete = "failed to delete Package"
)

type connector struct {
	kube client.Client
	opts []option
}

func (c *connector) Connect(ctx context.Context, mg cpresource.Managed) (managed.ExternalClient, error) {
	cr, ok := mg.(*svcapitypes.Package)
	if !ok {
		return nil, errors.New(errUnexpectedObject)
	}
	sess, err := awsclient.GetConfigV1(ctx, c.kube, mg, cr.Spec.ForProvider.Region)
	if err != nil {
		return nil, errors.Wrap(err, errCreateSession)
	}
	return newExternal(c.kube, svcapi.New(sess), c.opts), nil
}

func (e *external) Observe(ctx context.Context, mg cpresource.Managed) (managed.ExternalObservation, error) {
	cr, ok := mg.(*svcapitypes.Package)
	if !ok {
		return managed.ExternalObservation{}, errors.New(errUnexpectedObject)
	}
	if meta.GetExternalName(cr) == "" {
		return managed.ExternalObservation{
			ResourceExists: false,
		}, nil
	}
	input := GenerateDescribePackagesInput(cr)
	if err := e.preObserve(ctx, cr, input); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "pre-observe failed")
	}
	resp, err := e.client.DescribePackagesWithContext(ctx, input)
	if err != nil {
		return managed.ExternalObservation{ResourceExists: false}, awsclient.Wrap(cpresource.Ignore(IsNotFound, err), errDescribe)
	}
	resp = e.filterList(cr, resp)
	if len(resp.PackageDetailsList) == 0 {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}
	currentSpec := cr.Spec.ForProvider.DeepCopy()
	if err := e.lateInitialize(&cr.Spec.ForProvider, resp); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "late-init failed")
	}
	GeneratePackage(resp).Status.AtProvider.DeepCopyInto(&cr.Status.AtProvider)

	upToDate, err := e.isUpToDate(cr, resp)
	if err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, "isUpToDate check failed")
	}
	return e.postObserve(ctx, cr, resp, managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: upToDate,
		ResourceLateInitialized: !cmp.Equal(&cr.Spec.ForProvider, currentSpec),
	}, nil)
}

func (e *external) Create(ctx context.Context, mg cpresource.Managed) (managed.ExternalCreation, error) {
	cr, ok := mg.(*svcapitypes.Package)
	if !ok {
		return managed.ExternalCreation{}, errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Creating())
	input := GenerateCreatePackageInput(cr)
	if err := e.preCreate(ctx, cr, input); err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, "pre-create failed")
	}
	resp, err := e.client.CreatePackageWithContext(ctx, input)
	if err != nil {
		return managed.ExternalCreation{}, awsclient.Wrap(err, errCreate)
	}

	if resp.PackageDetails.AvailablePackageVersion != nil {
		cr.Status.AtProvider.AvailablePackageVersion = resp.PackageDetails.AvailablePackageVersion
	} else {
		cr.Status.AtProvider.AvailablePackageVersion = nil
	}
	if resp.PackageDetails.CreatedAt != nil {
		cr.Status.AtProvider.CreatedAt = &metav1.Time{*resp.PackageDetails.CreatedAt}
	} else {
		cr.Status.AtProvider.CreatedAt = nil
	}
	if resp.PackageDetails.ErrorDetails != nil {
		f2 := &svcapitypes.ErrorDetails{}
		if resp.PackageDetails.ErrorDetails.ErrorMessage != nil {
			f2.ErrorMessage = resp.PackageDetails.ErrorDetails.ErrorMessage
		}
		if resp.PackageDetails.ErrorDetails.ErrorType != nil {
			f2.ErrorType = resp.PackageDetails.ErrorDetails.ErrorType
		}
		cr.Status.AtProvider.ErrorDetails = f2
	} else {
		cr.Status.AtProvider.ErrorDetails = nil
	}
	if resp.PackageDetails.LastUpdatedAt != nil {
		cr.Status.AtProvider.LastUpdatedAt = &metav1.Time{*resp.PackageDetails.LastUpdatedAt}
	} else {
		cr.Status.AtProvider.LastUpdatedAt = nil
	}
	if resp.PackageDetails.PackageDescription != nil {
		cr.Spec.ForProvider.PackageDescription = resp.PackageDetails.PackageDescription
	} else {
		cr.Spec.ForProvider.PackageDescription = nil
	}
	if resp.PackageDetails.PackageID != nil {
		cr.Status.AtProvider.PackageID = resp.PackageDetails.PackageID
	} else {
		cr.Status.AtProvider.PackageID = nil
	}
	if resp.PackageDetails.PackageName != nil {
		cr.Spec.ForProvider.PackageName = resp.PackageDetails.PackageName
	} else {
		cr.Spec.ForProvider.PackageName = nil
	}
	if resp.PackageDetails.PackageStatus != nil {
		cr.Status.AtProvider.PackageStatus = resp.PackageDetails.PackageStatus
	} else {
		cr.Status.AtProvider.PackageStatus = nil
	}
	if resp.PackageDetails.PackageType != nil {
		cr.Spec.ForProvider.PackageType = resp.PackageDetails.PackageType
	} else {
		cr.Spec.ForProvider.PackageType = nil
	}

	return e.postCreate(ctx, cr, resp, managed.ExternalCreation{}, err)
}

func (e *external) Update(ctx context.Context, mg cpresource.Managed) (managed.ExternalUpdate, error) {
	cr, ok := mg.(*svcapitypes.Package)
	if !ok {
		return managed.ExternalUpdate{}, errors.New(errUnexpectedObject)
	}
	input := GenerateUpdatePackageInput(cr)
	if err := e.preUpdate(ctx, cr, input); err != nil {
		return managed.ExternalUpdate{}, errors.Wrap(err, "pre-update failed")
	}
	resp, err := e.client.UpdatePackageWithContext(ctx, input)
	return e.postUpdate(ctx, cr, resp, managed.ExternalUpdate{}, awsclient.Wrap(err, errUpdate))
}

func (e *external) Delete(ctx context.Context, mg cpresource.Managed) error {
	cr, ok := mg.(*svcapitypes.Package)
	if !ok {
		return errors.New(errUnexpectedObject)
	}
	cr.Status.SetConditions(xpv1.Deleting())
	input := GenerateDeletePackageInput(cr)
	ignore, err := e.preDelete(ctx, cr, input)
	if err != nil {
		return errors.Wrap(err, "pre-delete failed")
	}
	if ignore {
		return nil
	}
	resp, err := e.client.DeletePackageWithContext(ctx, input)
	return e.postDelete(ctx, cr, resp, awsclient.Wrap(cpresource.Ignore(IsNotFound, err), errDelete))
}

type option func(*external)

func newExternal(kube client.Client, client svcsdkapi.ElasticsearchServiceAPI, opts []option) *external {
	e := &external{
		kube:           kube,
		client:         client,
		preObserve:     nopPreObserve,
		postObserve:    nopPostObserve,
		lateInitialize: nopLateInitialize,
		isUpToDate:     alwaysUpToDate,
		filterList:     nopFilterList,
		preCreate:      nopPreCreate,
		postCreate:     nopPostCreate,
		preDelete:      nopPreDelete,
		postDelete:     nopPostDelete,
		preUpdate:      nopPreUpdate,
		postUpdate:     nopPostUpdate,
	}
	for _, f := range opts {
		f(e)
	}
	return e
}

type external struct {
	kube        client.Client
	client      svcsdkapi.ElasticsearchServiceAPI
	preObserve  func(context.Context, *svcapitypes.Package, *svcsdk.DescribePackagesInput) error
	postObserve func(context.Context, *svcapitypes.Package, *svcsdk.DescribePackagesOutput, managed.ExternalObservation, error) (managed.ExternalObservation, error)
	filterList func(*svcapitypes.Package, *svcsdk.DescribePackagesOutput) *svcsdk.DescribePackagesOutput
	lateInitialize func(*svcapitypes.PackageParameters, *svcsdk.DescribePackagesOutput) error
	isUpToDate     func(*svcapitypes.Package, *svcsdk.DescribePackagesOutput) (bool, error)
	preCreate   func(context.Context, *svcapitypes.Package, *svcsdk.CreatePackageInput) error
	postCreate  func(context.Context, *svcapitypes.Package, *svcsdk.CreatePackageOutput, managed.ExternalCreation, error) (managed.ExternalCreation, error)
	preDelete   func(context.Context, *svcapitypes.Package, *svcsdk.DeletePackageInput) (bool, error)
	postDelete  func(context.Context, *svcapitypes.Package, *svcsdk.DeletePackageOutput, error) error
	preUpdate   func(context.Context, *svcapitypes.Package, *svcsdk.UpdatePackageInput) error
	postUpdate  func(context.Context, *svcapitypes.Package, *svcsdk.UpdatePackageOutput, managed.ExternalUpdate, error) (managed.ExternalUpdate, error)
}
func nopPreObserve(context.Context, *svcapitypes.Package, *svcsdk.DescribePackagesInput) error {
	return nil
}
func nopPostObserve(_ context.Context, _ *svcapitypes.Package, _ *svcsdk.DescribePackagesOutput, obs managed.ExternalObservation, err error) (managed.ExternalObservation, error) {
	return obs, err
}
func nopFilterList(_ *svcapitypes.Package, list *svcsdk.DescribePackagesOutput) *svcsdk.DescribePackagesOutput {
	return list
}

func nopLateInitialize(*svcapitypes.PackageParameters, *svcsdk.DescribePackagesOutput) error {
	return nil
}
func alwaysUpToDate(*svcapitypes.Package, *svcsdk.DescribePackagesOutput) (bool, error) {
	return true, nil
}


func nopPreCreate(context.Context, *svcapitypes.Package, *svcsdk.CreatePackageInput) error {
	return nil
}
func nopPostCreate(_ context.Context, _ *svcapitypes.Package, _ *svcsdk.CreatePackageOutput, cre managed.ExternalCreation, err error) (managed.ExternalCreation, error) {
	return cre, err
}
func nopPreDelete(context.Context, *svcapitypes.Package, *svcsdk.DeletePackageInput) (bool, error) {
	return false, nil
}
func nopPostDelete(_ context.Context, _ *svcapitypes.Package, _ *svcsdk.DeletePackageOutput, err error) error {
	return err
}
func nopPreUpdate(context.Context, *svcapitypes.Package, *svcsdk.UpdatePackageInput) error {
	return nil
}
func nopPostUpdate(_ context.Context, _ *svcapitypes.Package, _ *svcsdk.UpdatePackageOutput, upd managed.ExternalUpdate, err error) (managed.ExternalUpdate, error) {
	return upd, err
}