/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package package

import (
	"github.com/aws/aws-sdk-go/aws/awserr"
	svcsdk "github.com/aws/aws-sdk-go/service/elasticsearchservice"

	svcapitypes "github.com/crossplane/provider-aws/apis/elasticsearchservice/v1alpha1"
)

// NOTE(muvaf): We return pointers in case the function needs to start with an
// empty object, hence need to return a new pointer.

// GenerateDescribePackagesInput returns input for read
// operation.
func GenerateDescribePackagesInput(cr *svcapitypes.Package) *svcsdk.DescribePackagesInput {
	res := &svcsdk.DescribePackagesInput{}


	return res
}

// GeneratePackage returns the current state in the form of *svcapitypes.Package.
func GeneratePackage(resp *svcsdk.DescribePackagesOutput) *svcapitypes.Package {
	cr := &svcapitypes.Package{}

	found := false
	for _, elem := range resp.PackageDetailsList {
		if elem.AvailablePackageVersion != nil {
			cr.Status.AtProvider.AvailablePackageVersion = elem.AvailablePackageVersion
		} else {
			cr.Status.AtProvider.AvailablePackageVersion = nil
		}
		if elem.CreatedAt != nil {
			cr.Status.AtProvider.CreatedAt = &metav1.Time{*elem.CreatedAt}
		} else {
			cr.Status.AtProvider.CreatedAt = nil
		}
		if elem.ErrorDetails != nil {
			f2 := &svcapitypes.ErrorDetails{}
			if elem.ErrorDetails.ErrorMessage != nil {
				f2.ErrorMessage = elem.ErrorDetails.ErrorMessage
			}
			if elem.ErrorDetails.ErrorType != nil {
				f2.ErrorType = elem.ErrorDetails.ErrorType
			}
			cr.Status.AtProvider.ErrorDetails = f2
		} else {
			cr.Status.AtProvider.ErrorDetails = nil
		}
		if elem.LastUpdatedAt != nil {
			cr.Status.AtProvider.LastUpdatedAt = &metav1.Time{*elem.LastUpdatedAt}
		} else {
			cr.Status.AtProvider.LastUpdatedAt = nil
		}
		if elem.PackageDescription != nil {
			cr.Spec.ForProvider.PackageDescription = elem.PackageDescription
		} else {
			cr.Spec.ForProvider.PackageDescription = nil
		}
		if elem.PackageID != nil {
			cr.Status.AtProvider.PackageID = elem.PackageID
		} else {
			cr.Status.AtProvider.PackageID = nil
		}
		if elem.PackageName != nil {
			cr.Spec.ForProvider.PackageName = elem.PackageName
		} else {
			cr.Spec.ForProvider.PackageName = nil
		}
		if elem.PackageStatus != nil {
			cr.Status.AtProvider.PackageStatus = elem.PackageStatus
		} else {
			cr.Status.AtProvider.PackageStatus = nil
		}
		if elem.PackageType != nil {
			cr.Spec.ForProvider.PackageType = elem.PackageType
		} else {
			cr.Spec.ForProvider.PackageType = nil
		}
		found = true
		break
	}
	if !found {
		return cr
	}

return cr
}

// GenerateCreatePackageInput returns a create input.
func GenerateCreatePackageInput(cr *svcapitypes.Package) *svcsdk.CreatePackageInput {
	res := &svcsdk.CreatePackageInput{}

	if cr.Spec.ForProvider.PackageDescription != nil {
		res.SetPackageDescription(*cr.Spec.ForProvider.PackageDescription)
	}
	if cr.Spec.ForProvider.PackageName != nil {
		res.SetPackageName(*cr.Spec.ForProvider.PackageName)
	}
	if cr.Spec.ForProvider.PackageSource != nil {
		f2 := &svcsdk.PackageSource{}
		if cr.Spec.ForProvider.PackageSource.S3BucketName != nil {
			f2.SetS3BucketName(*cr.Spec.ForProvider.PackageSource.S3BucketName)
		}
		if cr.Spec.ForProvider.PackageSource.S3Key != nil {
			f2.SetS3Key(*cr.Spec.ForProvider.PackageSource.S3Key)
		}
		res.SetPackageSource(f2)
	}
	if cr.Spec.ForProvider.PackageType != nil {
		res.SetPackageType(*cr.Spec.ForProvider.PackageType)
	}

	return res
}
// GenerateUpdatePackageInput returns an update input.
func GenerateUpdatePackageInput(cr *svcapitypes.Package) *svcsdk.UpdatePackageInput {
	res := &svcsdk.UpdatePackageInput{}

	if cr.Spec.ForProvider.PackageDescription != nil {
		res.SetPackageDescription(*cr.Spec.ForProvider.PackageDescription)
	}
	if cr.Status.AtProvider.PackageID != nil {
		res.SetPackageID(*cr.Status.AtProvider.PackageID)
	}
	if cr.Spec.ForProvider.PackageSource != nil {
		f3 := &svcsdk.PackageSource{}
		if cr.Spec.ForProvider.PackageSource.S3BucketName != nil {
			f3.SetS3BucketName(*cr.Spec.ForProvider.PackageSource.S3BucketName)
		}
		if cr.Spec.ForProvider.PackageSource.S3Key != nil {
			f3.SetS3Key(*cr.Spec.ForProvider.PackageSource.S3Key)
		}
		res.SetPackageSource(f3)
	}

	return res
}

// GenerateDeletePackageInput returns a deletion input.
func GenerateDeletePackageInput(cr *svcapitypes.Package) *svcsdk.DeletePackageInput {
	res := &svcsdk.DeletePackageInput{}

	if cr.Status.AtProvider.PackageID != nil {
		res.SetPackageID(*cr.Status.AtProvider.PackageID)
	}

	return res
}

// IsNotFound returns whether the given error is of type NotFound or not.
func IsNotFound(err error) bool {
	awsErr, ok := err.(awserr.Error)
	return ok && awsErr.Code() == "UNKNOWN" 
}