ignore:
  resource_names:
    - Listener
    - TargetGroup
    - Rule
  field_paths:
    - CreateLoadBalancerInput.Name
    - CreateLoadBalancerInput.SecurityGroups
    - CreateLoadBalancerInput.Subnets
    - DeleteLoadBalancerInput.Name
    - DeleteLoadBalancerInput.SecurityGroups
    - DeleteLoadBalancerInput.Subnets
